version: '3.4'
# This will handle the deployment of a local web application, postgresql
# database and elasticsearch single-node cluster

services:
    web:
      build:
          context: ./web
          dockerfile: Dockerfile
      image: uk.ac.wellcome/reach:latest
      ports:
        - 127.0.0.1:8081:8081
      environment:
        AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
        AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
        SENTRY_DSN: "${SENTRY_DSN}"
        STATIC_ROOT: /opt/reach/build/web/static
        DOCS_STATIC_ROOT: /opt/reach/web/docs/build/html/_static
        DB_HOST: "host.docker.internal"
        DB_PORT: 5432
        DB_NAME: "warehouse"
        DB_USER: "postgres"
        DB_PASSWORD: "development"

      command:
        - gunicorn
        - --bind=0.0.0.0:8081
        - --reload
        - web:application
      volumes:
        - ./web/web:/opt/reach/web/
      deploy:
        resources:
          limits:
            memory: "64M"
